#!/bin/bash

#SBATCH --job-name=fastqc # you can give your job a name
#SBATCH --nodes 1 # the number of processors or tasks
#SBATCH --cpus-per-task=2
#SBATCH --account=itcga # our account
#SBATCH --time=1:00:00 # the maximum time for the job
#SBATCH --mem=4gb # the amount of RAM
#SBATCH --partition=itcga # the specific server in chimera we are using
#SBATCH --reservation=2025_JUNE_ITCGA_WORKSHOP #This reservation lets us cut in line to use itcga cores
#SBATCH --error=logs/%x-%A_%a.err   # a filename to save error messages into
#SBATCH --output=logs/%x-%A_%a.out  # a filename to save any printed output into

echo "computer started!"

module load fastqc-0.11.9-gcc-10.2.0-osi6pqc

echo "fastqc loaded!"

fastqc -o   ../data/fastqc   ../data/untrimmed_fastq/*.fastq
